# Generated by Django 4.0.4 on 2022-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KMeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('cluster', models.IntegerField()),
                ('forest_area', models.FloatField()),
                ('inhabitable_area', models.FloatField()),
            ],
        ),
    ]
