# Generated by Django 4.0.4 on 2022-05-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmeans',
            name='high_schools',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='elementary_schools',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='hospitals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='junior_high_schools',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='kindergardens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='those_between_15_and_64',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='those_over_65',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='those_under_15',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='total_population',
            field=models.IntegerField(),
        ),
    ]
