# Generated by Django 4.0.4 on 2022-04-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kmeans',
            old_name='inhabitable_area',
            new_name='habitable_area',
        ),
    ]
