# Generated by Django 4.0.4 on 2022-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_kmeans'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('total_population', models.IntegerField()),
                ('those_under_15', models.IntegerField()),
                ('those_between_15_and_64', models.IntegerField()),
                ('those_over_65', models.IntegerField()),
                ('kindergardens', models.IntegerField()),
                ('elementary_schools', models.IntegerField()),
                ('junior_high_schools', models.IntegerField()),
                ('high_schools', models.IntegerField()),
                ('hospitals', models.IntegerField()),
                ('population_trends', models.FloatField()),
                ('move_in_ratio', models.FloatField()),
                ('move_out_ratio', models.FloatField()),
                ('primary_industry_ratio', models.FloatField()),
                ('secondary_industry_ratio', models.FloatField()),
                ('tertiary_industry_ratio', models.FloatField()),
                ('cluster', models.IntegerField()),
            ],
        ),
    ]
