# Generated by Django 4.0.4 on 2022-06-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kmeans',
            old_name='kindergardens',
            new_name='kindergartens',
        ),
    ]
